-- tables for storing data from Google Trends source 
-- This script creates the necessary schemas and tables for storing Google Trends data in etl proceses.

CREATE SCHEMA IF NOT EXISTS AIRFLOW_DB;

CREATE TABLE IF NOT EXISTS AIRFLOW_DB.interest_over_time (
    date TIMESTAMP NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    value FLOAT NOT NULL,
    channel VARCHAR(255) NOT NULL,
    schedule_interval VARCHAR(255) NOT NULL,
    geo_search VARCHAR(255),
    CONSTRAINT unique_interest_over_time UNIQUE (date, keyword, channel, schedule_interval, geo_search);
);

CREATE TABLE IF NOT EXISTS AIRFLOW_DB.interest_by_region (
    region VARCHAR(255) NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    value SMALLINT NOT NULL,
    schedule_interval VARCHAR(255) NOT NULL,
    load_date DATE NOT NULL,
    geo_search VARCHAR(255),
    CONSTRAINT unique_interest_by_region UNIQUE (region, keyword, schedule_interval, load_date);
);

-- REPORTS TABLES
-- These tables are used to store the results of the reports generated by the DAGs.
-- Superset will be used to visualize the data stored in these tables.
-- The reports are generated based on the data stored in the AIRFLOW_DB schema.

CREATE SCHEMA IF NOT EXISTS AIRFLOW_REPORTS;

CREATE TABLE IF NOT exists AIRFLOW_REPORTS.interest_by_region_report_new (
	region varchar(255) NULL,
	keyword varchar(255) NULL,
	value float8 NULL,
	category text NULL,
	load_date TIMESTAMP NULL
);
CREATE table IF NOT EXISTS AIRFLOW_REPORTS.interest_over_time_report_history (
    date DATE NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    category text NULL,
    avg_value DOUBLE PRECISION NOT NULL
);

CREATE table IF NOT EXISTS AIRFLOW_REPORTS.interest_over_time_report_avg_value_hour (
	hour_of_day text NULL,
	category text NULL,
	keyword varchar(255) NULL,
	avg_value float8 NULL
);
