log_level: "WARNING"

postgres:
  host: ${POSTGRES_HOST}
  db: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

email:
  sender: ${SENDER_EMAIL}
  sender_password: ${SENDER_EMAIL_PASSWORD}
  recipient: ${RECIPIENT_EMAIL}

pytrends_timeout: [20, 40]

pytrends_configs:
  - topic: data_visualization
    keywords: ["power bi", "tableau", "superset", "looker"]
    interest_by_region:
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 18 * * *"
    interest_over_time:
      timeframe: "now 1-d"
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 8 * * *"
  - topic: data_warehousing
    keywords: ["gcp", "azure", "AWS", "databricks", "snowflake"]
    interest_by_region:
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 20 * * *"
    interest_over_time:
      timeframe: "now 7-d"
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 10 * * *"
  - topic: programming_language
    keywords: ["Python", "java", "sql", "spark"]
    interest_over_time:
      timeframe: "now 1-d"
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 15 * * *"
    interest_by_region:
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "0 22 * * *"
  - topic: pl_popularity_profession
    keywords: ["data scientist", "data engineer", "bi developer", "data analyst", "data architect"]
    interest_over_time:
      timeframe: "now 1-d"
      category: 0
      geo: "PL"
      gprop: ""
      schedule_interval: "@daily"
    interest_by_region:
      category: 0
      geo: "PL"
      gprop: ""
      schedule_interval: "0 23 * * *"
  - topic: dependensy_work
    keywords: ["remote job", "work-life balance", "wellness", "productivity"]
    interest_over_time:
      timeframe: "today 1-m"
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "48 11 5 * *"
  - topic: dependensy_study
    keywords: ["tutorial", "learn", "course", "training", "webinar"]
    interest_over_time:
      timeframe: "today 1-m"
      category: 0
      geo: ""
      gprop: ""
      schedule_interval: "48 11 6 * *"